version: 2

shared:
  docker: &docker
    docker:
      - image: docker:stable

  clone-test: &clone-test
    name: Clone test project
    command: |
      git clone https://github.com/rawrtc/ci-image.git -b test-project test-project
  
  build-test: &build-test
    name: Build test project
    command: |
      cd test-project/build
      ninja install

  filters: &filters
    branches:
      only: cross/android


jobs:
  build-android-21-arm:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-21-arm android-21-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-21-arm

  test-android-21-arm:
    docker:
      - image: rawrtcdump/cross-build:android-21-arm

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-21-arm

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-21-arm:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-21-arm
            docker tag rawrtcdump/cross-build:android-21-arm rawrtc/cross-build:android-21-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-21-arm
  build-android-21-arm64:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-21-arm64 android-21-arm64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-21-arm64

  test-android-21-arm64:
    docker:
      - image: rawrtcdump/cross-build:android-21-arm64

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-21-arm64

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-21-arm64:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-21-arm64
            docker tag rawrtcdump/cross-build:android-21-arm64 rawrtc/cross-build:android-21-arm64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-21-arm64
  build-android-27-arm:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-27-arm android-27-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-27-arm

  test-android-27-arm:
    docker:
      - image: rawrtcdump/cross-build:android-27-arm

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-27-arm

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-27-arm:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-27-arm
            docker tag rawrtcdump/cross-build:android-27-arm rawrtc/cross-build:android-27-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-27-arm
  build-android-27-arm64:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-27-arm64 android-27-arm64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-27-arm64

  test-android-27-arm64:
    docker:
      - image: rawrtcdump/cross-build:android-27-arm64

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-27-arm64

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-27-arm64:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-27-arm64
            docker tag rawrtcdump/cross-build:android-27-arm64 rawrtc/cross-build:android-27-arm64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-27-arm64


workflows:
  version: 2

  # Push: Always build but only deploy on push to 'cross/android'
  push:
    jobs: &jobs
      - build-android-21-arm
      - test-android-21-arm:
          requires:
            - build-android-21-arm
      - deploy-android-21-arm:
          requires:
            - test-android-21-arm
          filters: *filters
      - build-android-21-arm64
      - test-android-21-arm64:
          requires:
            - build-android-21-arm64
      - deploy-android-21-arm64:
          requires:
            - test-android-21-arm64
          filters: *filters
      - build-android-27-arm
      - test-android-27-arm:
          requires:
            - build-android-27-arm
      - deploy-android-27-arm:
          requires:
            - test-android-27-arm
          filters: *filters
      - build-android-27-arm64
      - test-android-27-arm64:
          requires:
            - build-android-27-arm64
      - deploy-android-27-arm64:
          requires:
            - test-android-27-arm64
          filters: *filters

  # Monthly for 'cross/android' (after 'cross/base'): Build and deploy
  weekly:
    jobs: *jobs
    triggers:
      - schedule:
          cron: "0 6 1 * *"
          filters: *filters
