version: 2

shared:
  docker: &docker
    docker:
      - image: docker:stable

  clone-test: &clone-test
    name: Clone test project
    command: |
      git clone https://github.com/rawrtc/ci-image.git -b test-project test-project
  
  build-test: &build-test
    name: Build test project
    command: |
      cd test-project/build
      ninja install

  filters: &filters
    branches:
      only: cross/android


jobs:
  build-android-base:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-base android-base
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-base

  deploy-android-base:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-base
            docker tag rawrtcdump/cross-build:android-base rawrtc/cross-build:android-base
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-base
  
  build-android-16-arm:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-16-arm android-16-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-16-arm

  test-android-16-arm:
    docker:
      - image: rawrtcdump/cross-build:android-16-arm

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-16-arm

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-16-arm:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-16-arm
            docker tag rawrtcdump/cross-build:android-16-arm rawrtc/cross-build:android-16-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-16-arm
  build-android-16-x86:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-16-x86 android-16-x86
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-16-x86

  test-android-16-x86:
    docker:
      - image: rawrtcdump/cross-build:android-16-x86

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-16-x86

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-16-x86:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-16-x86
            docker tag rawrtcdump/cross-build:android-16-x86 rawrtc/cross-build:android-16-x86
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-16-x86
  build-android-28-arm:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-28-arm android-28-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-28-arm

  test-android-28-arm:
    docker:
      - image: rawrtcdump/cross-build:android-28-arm

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-28-arm

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-28-arm:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-28-arm
            docker tag rawrtcdump/cross-build:android-28-arm rawrtc/cross-build:android-28-arm
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-28-arm
  build-android-28-arm64:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-28-arm64 android-28-arm64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-28-arm64

  test-android-28-arm64:
    docker:
      - image: rawrtcdump/cross-build:android-28-arm64

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-28-arm64

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-28-arm64:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-28-arm64
            docker tag rawrtcdump/cross-build:android-28-arm64 rawrtc/cross-build:android-28-arm64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-28-arm64
  build-android-28-x86:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-28-x86 android-28-x86
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-28-x86

  test-android-28-x86:
    docker:
      - image: rawrtcdump/cross-build:android-28-x86

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-28-x86

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-28-x86:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-28-x86
            docker tag rawrtcdump/cross-build:android-28-x86 rawrtc/cross-build:android-28-x86
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-28-x86
  build-android-28-x86_64:
    <<: *docker

    steps:
      - checkout
      - setup_remote_docker

      # Build docker image
      - run:
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtcdump/cross-build:android-28-x86_64 android-28-x86_64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtcdump/cross-build:android-28-x86_64

  test-android-28-x86_64:
    docker:
      - image: rawrtcdump/cross-build:android-28-x86_64

    steps:

      # Clone test project
      - run: *clone-test

      # Configure test project
      - run:
          name: Configure test project
          command: |
            cd test-project
            mkdir build
            meson build --prefix /tmp/prefix --cross-file android-28-x86_64

      # Build test project
      - run: *build-test

      # Disabled, see: https://groups.google.com/forum/#!topic/mesonbuild/wTzIblOGs8w
      # Run test executable
      #- run:
      #    name: Run test executable
      #    command: |
      #      file /tmp/prefix/bin/test-executable

  deploy-android-28-x86_64:
    <<: *docker

    steps:
      - setup_remote_docker

      # Deploy docker image
      - deploy:
          name: Deploy docker image
          command: |
            docker pull rawrtcdump/cross-build:android-28-x86_64
            docker tag rawrtcdump/cross-build:android-28-x86_64 rawrtc/cross-build:android-28-x86_64
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/cross-build:android-28-x86_64


workflows:
  version: 2

  # Push: Always build but only deploy on push to 'cross/android'
  push:
    jobs: &jobs
      - build-android-base
      - deploy-android-base:
          requires:
            - build-android-base
          filters: *filters
      - build-android-16-arm:
          requires:
            - deploy-android-base
      - test-android-16-arm:
          requires:
            - build-android-16-arm
      - deploy-android-16-arm:
          requires:
            - test-android-16-arm
          filters: *filters
      - build-android-16-x86:
          requires:
            - deploy-android-base
      - test-android-16-x86:
          requires:
            - build-android-16-x86
      - deploy-android-16-x86:
          requires:
            - test-android-16-x86
          filters: *filters
      - build-android-28-arm:
          requires:
            - deploy-android-base
      - test-android-28-arm:
          requires:
            - build-android-28-arm
      - deploy-android-28-arm:
          requires:
            - test-android-28-arm
          filters: *filters
      - build-android-28-arm64:
          requires:
            - deploy-android-base
      - test-android-28-arm64:
          requires:
            - build-android-28-arm64
      - deploy-android-28-arm64:
          requires:
            - test-android-28-arm64
          filters: *filters
      - build-android-28-x86:
          requires:
            - deploy-android-base
      - test-android-28-x86:
          requires:
            - build-android-28-x86
      - deploy-android-28-x86:
          requires:
            - test-android-28-x86
          filters: *filters
      - build-android-28-x86_64:
          requires:
            - deploy-android-base
      - test-android-28-x86_64:
          requires:
            - build-android-28-x86_64
      - deploy-android-28-x86_64:
          requires:
            - test-android-28-x86_64
          filters: *filters

  # Monthly for 'cross/android' (after 'cross/base'): Build and deploy
  weekly:
    jobs: *jobs
    triggers:
      - schedule:
          cron: "0 6 1 * *"
          filters: *filters
