version: 2

shared: &shared
  docker:
    - image: docker:stable

jobs:
  # Build docker images
  build:
    <<: *shared
    steps:
      - checkout
      - setup_remote_docker
      - run: &build
          name: Build docker images
          command: |
            docker build --no-cache -t rawrtc/ci-image:trusty trusty
            docker build --no-cache -t rawrtc/ci-image:xenial xenial
            docker build --no-cache -t rawrtc/ci-image:bionic bionic
            docker build --no-cache -t rawrtc/ci-image:archlinux archlinux

  # Build and deploy docker images
  build-and-deploy:
    <<: *shared
    steps:
      - checkout
      - setup_remote_docker
      - run: *build
      - deploy:
          name: Deploy docker images
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push rawrtc/ci-image:trusty
            docker push rawrtc/ci-image:xenial
            docker push rawrtc/ci-image:bionic
            docker push rawrtc/ci-image:archlinux

workflows:
  version: 2

  # Push: Always build but only deploy on push to 'host/linux-x64'
  push:
    jobs: &jobs
      - build:
          filters:
            branches:
              ignore: &branch host/linux-x64
      - build-and-deploy:
          filters: &filters
            branches:
              only: *branch

  # Weekly for 'host/linux-x64': Build and deploy
  weekly:
    jobs: *jobs
    triggers:
      - schedule:
          cron: "0 5 * * 1"
          filters:
            branches:
              only: *branch

